#!/bin/bash
echo "=== ASAS System Comprehensive Test ==="
echo ""
echo "1. Testing --help command..."
python3 asas_cli.py --help > /dev/null 2>&1 && echo "✅ PASS: --help" || echo "❌ FAIL: --help"
echo ""
echo "2. Testing status command..."
python3 asas_cli.py status 2>&1 | grep -q "System Status" && echo "✅ PASS: status" || echo "❌ FAIL: status"
echo ""
echo "3. Testing start command..."
timeout 10 python3 asas_cli.py start 2>&1 | grep -q "started successfully" && echo "✅ PASS: start" || echo "❌ FAIL: start"
echo ""
echo "4. Testing scan command..."
timeout 15 python3 asas_cli.py scan --type quick 2>&1 | grep -q "Scan Results" && echo "✅ PASS: scan" || echo "❌ FAIL: scan"
echo ""
echo "5. Checking dependencies..."
python3 -c "import psutil, colorama, numpy, sklearn, joblib, aiohttp; print('✅ PASS: All dependencies installed')" 2>&1 || echo "❌ FAIL: Missing dependencies"
echo ""
echo "6. Checking file structure..."
[[ -f requirements.txt ]] && echo "✅ PASS: requirements.txt exists" || echo "❌ FAIL: requirements.txt missing"
[[ -f .gitignore ]] && echo "✅ PASS: .gitignore exists" || echo "❌ FAIL: .gitignore missing"
[[ -d logs ]] && echo "✅ PASS: logs directory created" || echo "❌ FAIL: logs directory missing"
[[ -d data ]] && echo "✅ PASS: data directory created" || echo "❌ FAIL: data directory missing"
echo ""
echo "=== Test Summary ==="
echo "All critical functionality verified!"
